namespace Diplom.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Diplom.DataContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(Diplom.DataContext context)
        {
            //context.Students.Add(new Student() { NameStudent = "Артем", SurName = "Балюк", SecondName = "Николаевич", Nationality = "Русский", DateBirth = Convert.ToDateTime("15.10.1999"), DateDocument = Convert.ToDateTime("05.07.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "077964652", MilitaryID = "1245725", House = "Одесская", Sex = "Мужской", Dormitories = "Нет", NumberGroup = "111", PhonePareant = "053324256", GPA = 4.78, Documents = "Аттестат", Estimates = "4,4,4,5,5,5,5", School = "МОУ ТСШ 7", EndSchool = Convert.ToDateTime("31.05.2016") });
            //context.Students.Add(new Student() { NameStudent = "Албина", SurName = "Буга", SecondName = "Алексеева", Nationality = "Русская", DateBirth = Convert.ToDateTime("02.01.2001"), DateDocument = Convert.ToDateTime("08.07.2016"), Social = "С отличием", ForeignLanguage = "Немецкий", Citizenship = "ПМР", Language = "Русский", Phone = "07785624", MilitaryID = "", House = "г.Тирасполь ул.Гагарина", Sex = "Женский", Dormitories = "Нет", NumberGroup = "111", PhonePareant = "053345264", GPA = 4.3, Documents = "Аттестат", Estimates = "4,3,5,3,3,5,4", School = "МОУ ТСШ 12", EndSchool = Convert.ToDateTime("31.05.2016") });
            //context.Students.Add(new Student() { NameStudent = "Адриан", SurName = "Голан", SecondName = "Андреевич", Nationality = "Молдован", DateBirth = Convert.ToDateTime("07.05.2001"), DateDocument = Convert.ToDateTime("01.08.2016"), Social = "", ForeignLanguage = "Немецкий", Citizenship = "Молдова", Language = "Русский", Phone = "", MilitaryID = "", House = "Молдова", Sex = "Мужской", Dormitories = "Да", NumberGroup = "111", PhonePareant = "053323456", GPA = 4.8, Documents = "Аттестат,Паспорт", Estimates = "4,4,5,5,5,5,5", School = "Молдавская школа №25", EndSchool = Convert.ToDateTime("30.06.2016") });
            //context.Students.Add(new Student() { NameStudent = "Махруза", SurName = "Гриб", SecondName = "Евгеньевна", Nationality = "Гагауз", DateBirth = Convert.ToDateTime("26.07.2000"), DateDocument = Convert.ToDateTime("08.07.2016"), Social = "Без попеч. родит.", ForeignLanguage = "Английский", Citizenship = "Гагаузия", Language = "Русский", Phone = "", MilitaryID = "", House = "Краснодонская", Sex = "Женский", Dormitories = "Да", NumberGroup = "111", PhonePareant = "053312856", GPA = 4, Documents = "Аттестат", Estimates = "4,4,4,4,4,4,4", School = "Гагаузкая школа №1", EndSchool = Convert.ToDateTime("16.05.2016") });
            //context.Students.Add(new Student() { NameStudent = "Яна", SurName = "Данильчук", SecondName = "Владимировна", Nationality = "Русская", DateBirth = Convert.ToDateTime("12.09.2000"), DateDocument = Convert.ToDateTime("09.07.2016"), Social = "С отличием", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "", MilitaryID = "", House = "ул.Пушкина", Sex = "Женский", Dormitories = "Нет", NumberGroup = "111", PhonePareant = "053353456", GPA = 5, Documents = "Аттестат", Estimates = "5,5,5,5,5,5,5,5", School = "МОУ ТСШ 12", EndSchool = Convert.ToDateTime("16.06.2016") });
            //context.Students.Add(new Student() { NameStudent = "Юрий", SurName = "Дарадур", SecondName = "Михайлович", Nationality = "Гагауз", DateBirth = Convert.ToDateTime("23.02.2000"), DateDocument = Convert.ToDateTime("10.07.2016"), Social = "", ForeignLanguage = "Немекций", Citizenship = "Гагаузия", Language = "Русский", Phone = "077985454", MilitaryID = "", House = "Гагаузия", Sex = "Мужской", Dormitories = "Да", NumberGroup = "111", PhonePareant = "053323526", GPA = 3.8, Documents = "Аттестат", Estimates = "4,5,5,5,3,3,3", School = "Гагаузкая школа №5", EndSchool = Convert.ToDateTime("16.06.2016") });
            //context.Students.Add(new Student() { NameStudent = "Артем", SurName = "Димитраш", SecondName = "Юрьевич", Nationality = "Молдован", DateBirth = Convert.ToDateTime("20.07.2000"), DateDocument = Convert.ToDateTime("21.07.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "Молдова", Language = "Русский", Phone = "077896554", MilitaryID = "", House = "Молдова", Sex = "Мужской", Dormitories = "Да", NumberGroup = "111", PhonePareant = "05775512", GPA = 4.2, Documents = "Аттестат", Estimates = "4,3,3,5,5,3,4", School = "Молдваская школа №23", EndSchool = Convert.ToDateTime("16.05.2016") });
            //context.Students.Add(new Student() { NameStudent = "Олег", SurName = "Бабков", SecondName = "Сергеевич", Nationality = "Русский", DateBirth = Convert.ToDateTime("07.03.2000"), DateDocument = Convert.ToDateTime("11.06.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "77995242", MilitaryID = "123585", House = "г.Тирасполь Гагарина 6", Sex = "Мужской", Dormitories = "Нет", NumberGroup = "112", PhonePareant = "053323456", GPA = 4.32, Documents = "Аттестат", Estimates = "4,3,5,5,3,5,4", School = "МОУ ТСШ 7", EndSchool = Convert.ToDateTime("16.06.2016") });
            //context.Students.Add(new Student() { NameStudent = "Аделина", SurName = "Бенц", SecondName = "Александровна", Nationality = "Молдованка", DateBirth = Convert.ToDateTime("15.09.2000"), DateDocument = Convert.ToDateTime("30.07.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "Молдова", Language = "Русский", Phone = "", MilitaryID = "", House = "Молдова г.Кишинев ул.Пушкина31", Sex = "Женский", Dormitories = "Да", NumberGroup = "112", PhonePareant = "", GPA = 4.78, Documents = "Аттестат", Estimates = "4,4,4,5,5,5,5", School = "Молдавская школа №12", EndSchool = Convert.ToDateTime("16.06.2016") });
            //context.Students.Add(new Student() { NameStudent = "Александр", SurName = "Березовский", SecondName = "Петрович", Nationality = "Руский", DateBirth = Convert.ToDateTime("08.08.2000"), DateDocument = Convert.ToDateTime("01.06.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "77856521", MilitaryID = "45684", House = "г.Тирасполь ул. Одесская", Sex = "Мужской", Dormitories = "Нет", NumberGroup = "112", PhonePareant = "053323456", GPA = 3.86, Documents = "Аттестат", Estimates = "4,3,3,3,5,3,4", School = "МОУ ТСШ 12", EndSchool = Convert.ToDateTime("16.06.2016") });
            //context.Students.Add(new Student() { NameStudent = "Анна", SurName = "Бутаку", SecondName = "Сергеевна", Nationality = "Русская", DateBirth = Convert.ToDateTime("22.10.2000"), DateDocument = Convert.ToDateTime("01.08.2016"), Social = "С отличием", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "7785424", MilitaryID = "", House = "г.Тирасполь ул.Краснодонская 82", Sex = "Женский", Dormitories = "Нет", NumberGroup = "112", PhonePareant = "", GPA = 5, Documents = "Аттестат", Estimates = "5,5,5,5,5,5,5,5", School = "МОУ ТСШ 5", EndSchool = Convert.ToDateTime("16.06.2016") });
            ////context.Students.Add(new Student() { NameStudent = "", SurName = "", SecondName = "", Nationality = "", DateBirth = Convert.ToDateTime("22.01.1999"), DateDocument = Convert.ToDateTime("01.07.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "", MilitaryID = "", House = "", Sex = "Женский", Dormitories = "Нет", NumberGroup = "", PhonePareant = "053323456", GPA = 4, Documents = "Аттестат", Estimates = "4,4,4,4,4,4,4", School = "МОУ ТСШ 12", EndSchool = Convert.ToDateTime("16.04.2016") });
            //context.Students.Add(new Student() { NameStudent = "", SurName = "", SecondName = "", Nationality = "", DateBirth = Convert.ToDateTime("22.01.1999"), DateDocument = Convert.ToDateTime("01.07.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "", MilitaryID = "", House = "", Sex = "Женский", Dormitories = "Нет", NumberGroup = "", PhonePareant = "053323456", GPA = 4, Documents = "Аттестат", Estimates = "4,4,4,4,4,4,4", School = "МОУ ТСШ 12", EndSchool = Convert.ToDateTime("16.04.2016") });
            //context.Students.Add(new Student() { NameStudent = "", SurName = "", SecondName = "", Nationality = "", DateBirth = Convert.ToDateTime("22.01.1999"), DateDocument = Convert.ToDateTime("01.07.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "", MilitaryID = "", House = "", Sex = "Женский", Dormitories = "Нет", NumberGroup = "", PhonePareant = "053323456", GPA = 4, Documents = "Аттестат", Estimates = "4,4,4,4,4,4,4", School = "МОУ ТСШ 12", EndSchool = Convert.ToDateTime("16.04.2016") });
            //context.Students.Add(new Student() { NameStudent = "", SurName = "", SecondName = "", Nationality = "", DateBirth = Convert.ToDateTime("22.01.1999"), DateDocument = Convert.ToDateTime("01.07.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "", MilitaryID = "", House = "", Sex = "Женский", Dormitories = "Нет", NumberGroup = "", PhonePareant = "053323456", GPA = 4, Documents = "Аттестат", Estimates = "4,4,4,4,4,4,4", School = "МОУ ТСШ 12", EndSchool = Convert.ToDateTime("16.04.2016") });
            //context.Students.Add(new Student() { NameStudent = "", SurName = "", SecondName = "", Nationality = "", DateBirth = Convert.ToDateTime("22.01.1999"), DateDocument = Convert.ToDateTime("01.07.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "", MilitaryID = "", House = "", Sex = "Женский", Dormitories = "Нет", NumberGroup = "", PhonePareant = "053323456", GPA = 4, Documents = "Аттестат", Estimates = "4,4,4,4,4,4,4", School = "МОУ ТСШ 12", EndSchool = Convert.ToDateTime("16.04.2016") });
            //context.Students.Add(new Student() { NameStudent = "", SurName = "", SecondName = "", Nationality = "", DateBirth = Convert.ToDateTime("22.01.1999"), DateDocument = Convert.ToDateTime("01.07.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "", MilitaryID = "", House = "", Sex = "Женский", Dormitories = "Нет", NumberGroup = "", PhonePareant = "053323456", GPA = 4, Documents = "Аттестат", Estimates = "4,4,4,4,4,4,4", School = "МОУ ТСШ 12", EndSchool = Convert.ToDateTime("16.04.2016") });
            //context.Students.Add(new Student() { NameStudent = "", SurName = "", SecondName = "", Nationality = "", DateBirth = Convert.ToDateTime("22.01.1999"), DateDocument = Convert.ToDateTime("01.07.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "", MilitaryID = "", House = "", Sex = "Женский", Dormitories = "Нет", NumberGroup = "", PhonePareant = "053323456", GPA = 4, Documents = "Аттестат", Estimates = "4,4,4,4,4,4,4", School = "МОУ ТСШ 12", EndSchool = Convert.ToDateTime("16.04.2016") });
            //context.Students.Add(new Student() { NameStudent = "", SurName = "", SecondName = "", Nationality = "", DateBirth = Convert.ToDateTime("22.01.1999"), DateDocument = Convert.ToDateTime("01.07.2016"), Social = "", ForeignLanguage = "Английский", Citizenship = "ПМР", Language = "Русский", Phone = "", MilitaryID = "", House = "", Sex = "Женский", Dormitories = "Нет", NumberGroup = "", PhonePareant = "053323456", GPA = 4, Documents = "Аттестат", Estimates = "4,4,4,4,4,4,4", School = "МОУ ТСШ 12", EndSchool = Convert.ToDateTime("16.04.2016") });
        }
    }
}
